# Generated by Django 4.2.6 on 2023-12-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.IntegerField(choices=[(1, '总监'), (2, '经理'), (3, '员工')], default=3, verbose_name='角色'),
        ),
    ]
