# Generated by Django 4.2.6 on 2023-12-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='部门')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('count', models.IntegerField(verbose_name='人数')),
            ],
        ),
    ]
