# Generated by Django 4.2.6 on 2024-01-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_userinfo_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NbUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=8, verbose_name='性别')),
            ],
        ),
    ]
